apiVersion: v1
kind: Secret
metadata:
    name: cronjobs-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    my.cnf: ENC[AES256_GCM,data:u3yUqujKNZHQKOM5V0wVAo5YL5DQknslaabYF5lpmcmxwETS+bnXjlnK1l0/kQ7lJaDPtQD5ZSSc6210035BAJQXoalMmSF8soM5iU9m3T/NSPHdZakxtZFvAU722716j5+/SeZlF+E/2yr96qjgCgTS1njzmCxPLZioeiU9xE4ECAAp3mL0xOhBds7TFcwxM4gMu3pvzZhnNSfIEtK6DvIzstfKiPOc4q6+n0AkmJnFsNHBKDB9gh7hMYyIG4I7Uw226fD1408zZo8ZBnZsDEi8TcjWWyyAZE7hrEZtSFlgNwK/fSopXGx8gK/0Cm8ymN90zPGj7RM+U1MJeG3qiOB75J08bTiEZAit/KTj9JzLF4MKKjesycvS,iv:gpzZmKZAAIh61hyTv+mdnp6KpQ9vayOs4SXkX4dWYh4=,tag:exjbGX9WNIgZNBThFDaX7A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-11-27T13:45:49Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFXxnfFaChIpJot/lj045WaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzUcAOHaVHBlYzZ+ZAgEQgDt6HwS1MSmJJeSicuyc/NJkMtVyAgAEe/QU+YJVPaLmxhzMqEXlkLo/C2ns/jeJ9ki7GeHHpmJq8udIpw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T07:04:01Z"
    mac: ENC[AES256_GCM,data:t+4U4j9uOT891y32q4s4c2oKTTUavkEYS2EIuBP/4GxkYxi2txZUOexkmL6hK3+rSRkOkvr9E/JT7bRthoHMYGx4nEViRf0h+uLxh1/a/S6jlmuC277zP3rIapJgqxpsmKbza/iKbP/v7SETeEA0BN26FhaNVKWp1xZZnFj/uyw=,iv:AUMyYyYvE8l/DfIoCfyj3YQPzzatomQSswW2t6JnMOA=,tag:DLAhguO9YuY9uGeQqszYaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
