apiVersion: v1
kind: Secret
metadata:
    name: llm-api-secret
type: Opaque
stringData:
    deepseek: ENC[AES256_GCM,data:PLACEHOLDER_ENCRYPTED_API_KEY,iv:PLACEHOLDER_IV,tag:PLACEHOLDER_TAG,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2025-08-28T00:00:00Z"
          enc: PLACEHOLDER_ENC_KEY
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-28T00:00:00Z"
    mac: ENC[AES256_GCM,data:PLACEHOLDER_MAC,iv:PLACEHOLDER_MAC_IV,tag:PLACEHOLDER_MAC_TAG,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
