apiVersion: v1
kind: Secret
metadata:
    name: llm-api-secret
type: Opaque
stringData:
    deepseek: ENC[AES256_GCM,data:zd7Z/Z4wzbJx7ixA96T070j7CXJbFSsBDEajd+qJq33qczo=,iv:PhOTbNajvLp6HHE6vPs1xJRu9XOBhlY5DiF9kqGvjHw=,tag:TuDSjztP+TWlRFtRbUKa6w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2025-08-22T07:39:28Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQHE+IvUCSGwWF7Ycnntq/sgAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfEMI7K0pYRUrjuRAAgEQgDuAJXsWJae5yrBbaXaHPbla0x7wMVyqYq70CreQ4P3ehUXrFGZMXvcSTDe/nqKoMG/uzFxJgAGlmmMWTA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-22T07:42:43Z"
    mac: ENC[AES256_GCM,data:Az6PQZ+q8vTqIvnGjkGqKNsOY5cy3EgLH2Xyy6emFtxeILeQuzkkKQ7oY3tjThHqKIJV7V7UkIPB5mLwp7THWKHbdapYoGpOiCGsjL6icOqSHJLggPgytfUmi70bFKZHoRYHZvu5GhZsSP08fPHiql62XiessyGMqsZ3uga4Pd0=,iv:UXj2OOqvNEqNbS4yeBuvLG8HtofrQSqBjliKqTE7Wz8=,tag:pS1uKsu2o92VNhthihI25Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
