apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

commonLabels:
  env: production

bases:
- ../../base
configMapGenerator:
- name: grafana-config
  files:
  - grafana-config/grafana.ini
- name: prometheus-config
  files:
  - prometheus-config/kubernetes-apiservers.yml
  - prometheus-config/kubernetes-endpoints.yml
  - prometheus-config/kubernetes-nodes.yml
  - prometheus-config/kubernetes-pods.yml
  - prometheus-config/kubernetes-services.yml
generators:
- grafana-secret-generator.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: grafana.omegaup.com
  target:
    name: grafana-ingress
    kind: Ingress
    group: networking.k8s.io
    version: v1
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: grafana-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/hsts: true
    spec:
      tls:
      - hosts:
        - grafana.omegaup.com
        secretName: grafana-ingress-cert
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grafana-deployment
    spec:
      template:
        spec:
          containers:
            - name: grafana
              volumeMounts:
              - name: grafana-config
                mountPath: /etc/grafana/grafana.ini
                subPath: grafana.ini
              - name: github-client-secret
                mountPath: /etc/secrets/github_client_secret
                readOnly: true
                subPath: github_client_secret
          volumes:
          - name: grafana-config
            configMap:
              name: grafana-config
          - name: github-client-secret
            secret:
              secretName: grafana-secret
              items:
                - key: github-client-secret
                  path: github_client_secret
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: prometheus-deployment
    spec:
      template:
        spec:
          containers:
            - name: prometheus
              volumeMounts:
              - name: prometheus-config
                mountPath: /etc/prometheus.tmpl/kubernetes-apiservers.yml
                subPath: kubernetes-apiservers.yml
              - name: prometheus-config
                mountPath: /etc/prometheus.tmpl/kubernetes-endpoints.yml
                subPath: kubernetes-endpoints.yml
              - name: prometheus-config
                mountPath: /etc/prometheus.tmpl/kubernetes-nodes.yml
                subPath: kubernetes-nodes.yml
              - name: prometheus-config
                mountPath: /etc/prometheus.tmpl/kubernetes-pods.yml
                subPath: kubernetes-pods.yml
              - name: prometheus-config
                mountPath: /etc/prometheus.tmpl/kubernetes-services.yml
                subPath: kubernetes-services.yml
          volumes:
          - name: prometheus-config
            configMap:
              name: prometheus-config
