apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.1/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.2.1/manifests/install.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.2.1/catalog/install.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-metrics
      annotations:
        prometheus.io/port: '8082'
        prometheus.io/scrape: 'true'
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-server-metrics
      annotations:
        prometheus.io/port: '8083'
        prometheus.io/scrape: 'true'
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-notifications-controller-metrics
      annotations:
        prometheus.io/port: '9001'
        prometheus.io/scrape: 'true'
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: argocd-application-controller
    spec:
      template:
        spec:
          containers:
          - name: argocd-application-controller
            resources:
              requests:
                cpu: 2m
                memory: 70Mi
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-dex-server
    spec:
      template:
        spec:
          containers:
          - name: dex
            resources:
              requests:
                cpu: 1m
                memory: 20Mi
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-notifications-controller
    spec:
      template:
        spec:
          containers:
          - name: argocd-notifications-controller
            resources:
              requests:
                cpu: 1m
                memory: 32Mi
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-redis
    spec:
      template:
        spec:
          containers:
          - name: redis
            resources:
              requests:
                cpu: 2m
                memory: 5Mi
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-repo-server
    spec:
      template:
        spec:
          containers:
          - name: argocd-repo-server
            resources:
              requests:
                cpu: 3m
                memory: 52Mi
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-server
    spec:
      template:
        spec:
          containers:
          - name: argocd-server
            resources:
              requests:
                cpu: 3m
                memory: 30Mi
