apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: frontend
        app.kubernetes.io/component: omegaup-frontend
    spec:
      containers:
      - name: php
        image: omegaup/php
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
        - name: frontend-secret
          mountPath: /etc/omegaup/frontend
        - name: omegaup-secret
          mountPath: /opt/omegaup/frontend/server/config.php
          subPath: config.php
        - name: php-config
          mountPath: /etc/php/8.0/fpm/php-fpm.conf
          subPath: php-fpm.conf
        - name: omegaup
          mountPath: /opt/omegaup
        - name: varlog
          mountPath: /var/log
        - name: runphp
          mountPath: /run/php
      - name: nginx
        image: omegaup/nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        - name: liveness-port
          containerPort: 8090
        readinessProbe:
          httpGet:
            path: /stub_status
            port: liveness-port
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /stub_status
            port: liveness-port
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
        - name: omegaup
          mountPath: /opt/omegaup
        - name: varlibomegaup
          mountPath: /var/lib/omegaup
        - name: varlog
          mountPath: /var/log
        - name: runphp
          mountPath: /run/php
      - name: fluent-bit
        image: fluent/fluent-bit:1.8
        command: ['/fluent-bit/bin/fluent-bit', '--quiet', '-c', '/fluent-bit/etc/fluent-bit.conf']
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
      initContainers:
      - name: init-varlog
        image: busybox:1.28
        command: ['sh', '-c', 'touch /var/log/frontend.log /var/log/nginx.access.log /var/log/nginx.error.log']
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      - name: init-volume
        image: omegaup/frontend
        imagePullPolicy: IfNotPresent
        # TODO: Make this ; an &&.
        command: ['sh', '-c', 'rsync -az /var/lib/omegaup/ /mnt/lib/ ; rsync -az /opt/omegaup/ /mnt/omegaup/']
        volumeMounts:
        - name: omegaup
          mountPath: /mnt/omegaup
        - name: varlibomegaup
          mountPath: /mnt/lib
      volumes:
      - name: frontend-secret
        secret:
          secretName: frontend-secret
      - name: omegaup-secret
        secret:
          secretName: omegaup-secret
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: php-config
        configMap:
          name: php-config
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: varlog
        emptyDir: {}
      - name: omegaup
        emptyDir: {}
      - name: varlibomegaup
        emptyDir: {}
      - name: runphp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: frontend
  annotations:
    prometheus.io/port: '8000'
    prometheus.io/scrape: 'true'
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
  labels:
    app.kubernetes.io/name: static
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: static
  template:
    metadata:
      labels:
        app.kubernetes.io/name: static
        app.kubernetes.io/part-of: static
        app.kubernetes.io/component: omegaup-frontend
    spec:
      containers:
      - name: static
        image: omegaup/static:20220104-2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: static-service
  labels:
    app.kubernetes.io/name: static
spec:
  selector:
    app.kubernetes.io/name: static
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "125"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "125"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "125"
spec:
  rules:
  - host: omegaup.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8000
      - path: /docs/cpp/
        pathType: Prefix
        backend:
          service:
            name: static-service
            port:
              number: 80
      - path: /docs/java/
        pathType: Prefix
        backend:
          service:
            name: static-service
            port:
              number: 80
      - path: /docs/pas/
        pathType: Prefix
        backend:
          service:
            name: static-service
            port:
              number: 80
      - path: /docs/assets/
        pathType: Prefix
        backend:
          service:
            name: static-service
            port:
              number: 80
