apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

resources:
- deployment.yaml
- cronjobs.yaml
- redis.yaml
- db-migrate.yaml
- ai-editorial-worker.yaml

configMapGenerator:
- name: fluent-bit-config
  files:
  - fluent-bit-config/fluent-bit.conf
  - fluent-bit-config/parsers.conf
  - fluent-bit-config/output.conf
- name: php-config
  files:
  - php-config/php-fpm.conf
- name: nginx-config
  files:
  - nginx-config/nginx.conf
  - nginx-config/mime.types

secretGenerator:
- files:
  - cronjobs-secret/my.cnf
  name: cronjobs-secret
