apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup-sandbox

metadata:
  name: kustomization
  namespace: omegaup-sandbox

commonLabels:
  env: sandbox

generators:
- grader-secret-generator.yaml
- gitserver-secret-generator.yaml
- runner-secret-generator.yaml

resources:
- ../../../base/backend
- backend.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grader-deployment
    spec:
      template:
        spec:
          containers:
          - name: grader
            resources:
              limits:
                memory: 64Mi
- path: gitserver-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: gitserver-deployment
    version: v1
- path: grader-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: grader-deployment
    version: v1
- path: broadcaster-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: broadcaster-deployment
    version: v1
- path: runner-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: runner-deployment
    version: v1

images:
- name: omegaup/backend
  newTag: v1.9.52
- name: omegaup/gitserver
  newTag: v1.9.17
- name: omegaup/runner
  newTag: v1.9.52
