apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup-development

metadata:
  name: kustomization
  namespace: omegaup-development

commonLabels:
  env: development

secretGenerator:
- files:
  - omegaup-secret/config.php
  name: omegaup-secret
- files:
  - frontend-secret/certificate.pem
  - frontend-secret/key.pem
  name: frontend-secret
- files:
  - runner-secret/config.json
  - runner-secret/certificate.pem
  - runner-secret/key.pem
  name: runner-secret
- files:
  - redis-secret/redis.conf
  name: redis-secret

configMapGenerator:
- behavior: merge
  files:
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf
  - nginx-config/realip.conf
  name: nginx-config

resources:
- ../../base/frontend
- ../../base/backend
- database.yaml
- backend.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
    spec:
      replicas: 1
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: omegaup.test
  target:
    group: networking.k8s.io
    kind: Ingress
    name: frontend-ingress
    version: v1
- patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: db-migrate
    spec:
      template:
        spec:
          containers:
          - name: db-migrate
            command: [
              '/opt/omegaup/stuff/db-migrate.py',
              '--verbose',
              '--log-json',
              '--lower-timeout',
              '--kill-blocking-connections',
              '--username=root',
              '--password=omegaup',
              '--hostname=mysql-service',
              '--port=13306',
              'migrate',
              '--databases=omegaup',
              '--development-environment',
            ]
images:
- name: omegaup/frontend
  newTag: latest-main
- name: omegaup/frontend-sidecar
  newTag: latest-main
- name: omegaup/nginx
  newTag: latest-main
- name: omegaup/php
  newTag: latest-main
